### PR TITLE
Dropbox v2 API

### PR DESCRIPTION
**Pull request by roborourke**
Adds a custom dropbox API that should support PHP 5.3+

### CODE REVIEW

**Comment by katmoody** [comment]
@roborourke -- I left a note in Slack - I have a database backup (over 1 GB) still uploading to Dropbox an hour later. With the newer chunked upload feature, how long should bigger uploads expect to take to Dropbox and when would you know if they failed?

**Comment by roborourke** [comment]
That’ll take a long time anyway. It’s doing 8Mb at a time but we can maybe
try and increase that with more testing. Also depends on their available
bandwidth from the machine. You’d only know it failed when it stopped
normally, it might still be running. Can test with a bigger backup this
weekend.

How long did it used to take?

**Comment by katmoody** [comment]
So far it's taken 2 hours, @roborourke - my concern is that if it is taking that long to upload to Dropbox, what's keeping it from running into the `max_execution_time` or other server limitations for outgoing connections? Does it count is as separate processes for each 8 MB?

**Comment by roborourke** [comment]
Depends on the internals of BWP that I’m not so familiar with. I’ll run a
test. From what I could gather it’s exactly how the other ones work :/

**Comment by pdewouters** [comment]
yes, the way @roborourke coded the new version won't be less efficient as the previous one, as it already used chunked uploads but via an SDK method. It would be good to test with a 30 seconds max execution time.

**Comment by roborourke** [comment]
I successfully ran a 1Gb backup & upload, took about 15 minutes, the
problem was a memory leak that I've worked around. I've added in various
`$backup->warning()` calls but we could do a bunch to recover from or
continue with an upload session should it fail or time out if we store the
upload session ID and previous byte offset.

**Comment by katmoody** [comment]
So far we've had a few tentative successes but I'm just getting ready to check in on Intercom. 

From prior experience, @roborourke, I can say that memory issues, execution time and other various server limits can cause the most issues. I'd be interested in seeing how it holds up through additional testing. 

Curious about testing specifically with that 30 second max execution time as @pdewouters mentioned above, so will try to do that if I can :grin:

**Comment by roborourke** [comment]
Yeah we generally shouldn't hit that issue as it's run in a background
process and the BWP core does a few things to boost the execution time and
memory limit while doing those things. If all the other upload addons are
managing then this one should be no different now in theory. Glad it's been
working so far! Keep us posted and we'll get a release out ASAP.

**Pull request merged**
